### ISSUE TITLE
Duplicate calendar events

### ISSUE THREAD

**Issue by aaronmathews95** [revabam/bambam-client#65]
When getting existing calendar-events to populate the calendar for ngOnInit, duplicate objects are present on several days. This could be from creating the events and duplicates are placed in data.json, or the algorithm for retrieving them is incorrect and creating the duplicates.

**Comment by BrandonScoggins44** [comment]
This issue was due to the event loop. Several database calls were queued up immediately after each other, and each was referencing the same global variables. This caused some of the entries to have the same values when stored. The issue was solved by using the same logic to queue up the database calls to instead push the events into an array. Then after the array was filled, we could store the entire array, or each object individually since they were no longer referencing the global variables.
